---
# this playbook joins a RHEL server to a Windows AD domain
# It depend on external (extra) vars to supply the domain name and the other
# variables
- name: join a server to a Domain
  become: yes
  hosts: linux
  vars_files:
    - files/join_domain_vars

  tasks:
  - name: set timezone to Europe/Amsterdam
    timezone:
      name: Europe/Amsterdam
      hwclock: UTC
    tags:
      - time

  - name: Install AD related software
    yum:
      name: ['krb5-workstation', 'samba-common-tools', 'sssd-ad', 'oddjob-mkhomedir']
      state: installed
    tags:
      - packages

  - include_role:
      name: geerlingguy.ntp
    tags:
      - time

  - name: configure Kerberos
    template:
      src: files/krb5.conf.j2
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: 0644
    tags:
      - krb5

  - name: configure Samba
    template:
      src: files/smb.conf.j2
      dest: /etc/samba/smb.conf
      owner: root
      group: root
      mode: 0644
    tags:
      - smb

  - name: get admin credentials
    shell: |
      echo {{ ad_password }} | kinit {{ ad_user }}
    tags:
      - krb5

  - name: join machine to domain
    shell: |
      net ads join -k
    args:
      creates: /etc/krb5.keytab
    tags:
      - krb5

  - name: remove admin credentials
    shell: |
      kdestroy
    tags:
      - krb5

  - name: place pam and authconfig configuration files, fingerprint-auth-ac
    copy:
      src: files/fingerprint-auth-ac
      dest: /etc/pam.d/fingerprint-auth-ac
      owner: root
      group: root
      mode: 0644
    tags:
      - pam

  - name: place pam and authconfig configuration files, password-auth-ac
    copy:
      src: files/password-auth-ac
      dest: /etc/pam.d/password-auth-ac
      owner: root
      group: root
      mode: 0644
    tags:
      - pam

  - name: place pam and authconfig configuration files, smartcard-auth-ac
    copy:
      src: files/smartcard-auth-ac
      dest: /etc/pam.d/smartcard-auth-ac
      owner: root
      group: root
      mode: 0644
    tags:
      - pam

  - name: place pam and authconfig configuration files, system-auth-ac
    copy:
      src: files/system-auth-ac
      dest: /etc/pam.d/system-auth-ac
      owner: root
      group: root
      mode: 0644
    tags:
      - pam

  - name: place pam and authconfig configuration files, authconfig
    copy:
      src: files/authconfig
      dest: /etc/sysconfig/authconfig
      owner: root
      group: root
      mode: 0644
    tags:
      - pam

  - name: configure sssd
    template:
      src: files/sssd.conf.j2
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: 0600
    tags:
      - sssd

  - name: start sssd
    service:
      name: sssd
      state: started
      enabled: yes
    tags:
      - sssd

  - name: place sudoers file for domain admins
    copy:
      src: files/domain_admins_sudoers
      dest: /etc/sudoers.d/domain_admins_sudoers
      owner: root
      group: root
      mode: 0400
    tags:
      - sudo
